spring:
  #  profiles:
  #    active: lcoal
  config:
    activate:
      on-profile:
        - prod
  data:
    mongodb:
      uri: mongodb+srv://lijinming:lijinmin@ljm0.e9q9sme.mongodb.net/?retryWrites=true&w=majority
server:
  port: 9002
